package com.abc;

import java.util.ArrayList;
import java.util.List;

import static java.lang.Math.abs;

/**
 * This is the class for the Customer.
 * It contains an ArrayList of the Accounts held by the customer.
 * @author Matthew Howard - <a href="mailto:m.o.howard@outlook.com">m.o.howard@outlook.com</a>
 */

public class Customer {
    private String name;
    private List<Account> accounts;

    /**
     * This is the constructor for the Customer class. It takes a name to give the customer and a Bank to register the customer with.
     * @param name A String representing the name of this Customer
     * @param bank  A Bank that this Customer shall be registered with
     */
    public Customer(String name, Bank bank) {
        this.name = name;
        this.accounts = new ArrayList<Account>();
        bank.addCustomer(this);
    }

    /**
     * This function returns the name of the Customer
     * @return  The String that represents this Customer's name
     */
    public String getName() {
        return name;
    }

    /**
     * This function creates a new Account and adds it to the LinkedList of Accounts belonging to this Customer
     * @param accountType  An integer between 0 and 2 representing CHECKING, SAVINGS, and MAXI_SAVINGS. See Account docs for more info.
     * @return The new Account object generated by this function.
     */
    public Account openAccount(int accountType) {
        Account newAcc = new Account(accountType);
        accounts.add(newAcc);
        return newAcc;
    }

    /**
     * A function that returns the number of Accounts held by this Customer.
     * @return An Integer which describes how many Accounts this Customer has
     */
    public int getNumberOfAccounts() {
        return accounts.size();
    }

    /**
     * This function works out the total amount of interest earned in a year across all Accounts held by this Customer.
     * @return  A double representing the amount of monetary interest earned in a year across all Accounts held by this Customer
     */
    public double totalInterestEarned() {
        double total = 0;
        for (Account a : accounts)
            total += a.interestEarned();
        return total;
    }

    /**
     * This function generates a nicely formatted String describing the list of Transactions in all Accounts held by this Customer
     * @return A nicely formatted String describing the list of Transactions in all Accounts held by this Customer
     */
    public String getStatement() {
        String statement = "Statement for " + name + "\n";
        double total = 0.0;
        for (Account a : accounts) {
            statement += "\n" + statementForAccount(a) + "\n";
            total += a.sumTransactions();
        }
        statement += "\nTotal In All Accounts " + toDollars(total);
        return statement;
    }

    /**
     * A function that transfers a given amount of money from one given account to another given account.
     * @param from An Account from which the money shall be withdrawn.
     *             If the Account does not have enough funds, an IllegalArgumentException will be thrown
     *             If the Account does not belong to this Customer an IllegalArgumentException will be thrown
     * @param to The Account which the money shall be deposited into.
     *             If the Account does not have enough funds, an IllegalArgumentException will be thrown
     *             If the Account does not belong to this Customer an IllegalArgumentException will be thrown
     * @param amount A double representing the amount of money to be transferred from the first Account to the second
     *               The double must not have more than 2 decimal places as it is impossible to have 0.001 dollars
     *               The double must not be negative
     */
    public void transferFundsBetweenAccounts(Account from, Account to, double amount){
        boolean fromExists = false;
        boolean toExists = false;
        for(int i = 0; i< accounts.size();i++){
            if (accounts.get(i) == from) {
                fromExists = true;
            }
            if(accounts.get(i) == to){
                toExists= true;
            }
        }
        if(fromExists&&toExists){
            from.withdraw(amount);
            to.deposit(amount);
        } else{
            throw new IllegalArgumentException("both accounts must belong to this customer");
        }
    }

    /**
     * This function returns a neatly formatted String describing the Transactions for a given Account
     * @param a This is the Account for which a statement will be generated
     * @return A neatly formatted String describing the Transactions of the given Account
     */
    private String statementForAccount(Account a) {
        String s = "";

        //Translate to pretty account type
        switch(a.getAccountType()){
            case Account.CHECKING:
                s += "Checking Account\n";
                break;
            case Account.SAVINGS:
                s += "Savings Account\n";
                break;
            case Account.MAXI_SAVINGS:
                s += "Maxi Savings Account\n";
                break;
        }

        //Now total up all the transactions
        double total = 0.0;
        for (Transaction t : a.transactions) {
            s += "  " + (t.getAmount() < 0 ? "withdrawal" : "deposit") + " " + toDollars(t.getAmount()) + "\n";
            total += t.getAmount();
        }
        s += "Total " + toDollars(total);
        return s;
    }

    /**
     * A function that converts a given double into a properly formatted String representing that figure in dollars
     * @param d A double to be converted into a String representing dollars
     * @return  A String representing the given amount with a dollar sign and rounded to 2 decimal places
     */
    private String toDollars(double d){
        return String.format("$%,.2f", abs(d));
    }
}
